import streamlit as st
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from groq import Groq

# ──────────────────────────────────────────────────────────────────────────────
# WHY THIS FILE EXISTS
#
# This file handles the two core operations of a RAG (Retrieval-Augmented
# Generation) system:
#
#   RETRIEVAL: Given a question, find the most relevant text chunks in FAISS.
#   GENERATION: Feed those chunks as context to the LLM and stream the answer.
#
# The architecture is:
#   User question
#       ↓
#   Convert question to a 384-dim embedding vector (same model used at index time)
#       ↓
#   FAISS finds the 4 most similar chunk vectors (cosine similarity)
#       ↓
#   Build a prompt: system instructions + retrieved context + chat history + question
#       ↓
#   Groq streams the answer token by token
#       ↓
#   Return (stream generator, source Document objects)
# ──────────────────────────────────────────────────────────────────────────────


# ── @st.cache_resource ────────────────────────────────────────────────────────
# This decorator is crucial for performance.
#
# Without it: every time the user types a message, Streamlit reruns app.py,
# which calls get_embeddings(), which downloads the ~80 MB model AGAIN.
# That would be 30-60 seconds of latency per query. Unusable.
#
# With it: the model is loaded ONCE and kept in memory for the entire session.
# Subsequent calls return the cached object instantly.
#
# @st.cache_resource is for objects that should NOT be copied between runs
# (like ML models, database connections). It's different from @st.cache_data
# which is for data/serializable objects.
@st.cache_resource
def get_embeddings() -> HuggingFaceEmbeddings:
    """
    Load the all-MiniLM-L6-v2 sentence transformer model.

    This model converts text into 384-dimensional vectors.
    The SAME model must be used both when building the index and when
    querying it — the vectors only make sense relative to each other
    if they were generated by the same model.

    all-MiniLM-L6-v2 is a good choice for RAG because:
    - Fast on CPU (no GPU needed for Streamlit Cloud)
    - Small model size (~80 MB)
    - Strong semantic understanding for English text
    - Free via HuggingFace (no API key required)
    """
    return HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2",
        model_kwargs={"device": "cpu"},      # Force CPU — Streamlit Cloud has no GPU
        encode_kwargs={"normalize_embeddings": True}  # Normalise for cosine similarity
    )


def build_vector_store(chunks: list, embeddings: HuggingFaceEmbeddings) -> FAISS:
    """
    Convert text chunks into embedding vectors and build a FAISS index.

    What happens here:
    1. Each chunk's text is passed through the embedding model → 384-dim vector
    2. All vectors are stored in a FAISS IndexFlatL2 (exact nearest-neighbour search)
    3. The metadata dict (source, page) is stored alongside each vector
    4. The whole structure lives in RAM — fast to search, gone when session ends

    Args:
        chunks:     List of LangChain Document objects from document_processor.py
        embeddings: The cached HuggingFaceEmbeddings model

    Returns:
        A FAISS vector store ready to query
    """
    # FAISS.from_documents() handles the embedding + indexing in one call.
    # It embeds all chunks in batch (more efficient than one at a time),
    # then builds the FAISS index structure.
    vector_store = FAISS.from_documents(chunks, embeddings)
    return vector_store


def query_documents(
    query: str,
    vector_store: FAISS,
    chat_history: list[tuple]
) -> tuple:
    """
    Find relevant chunks for a question and stream an LLM answer.

    Two-phase process:
      Phase 1 (Retrieval): FAISS similarity search — pure vector math, ~10ms
      Phase 2 (Generation): Groq LLM with retrieved context — ~1-3 seconds streaming

    Args:
        query:         The user's question
        vector_store:  The FAISS index built from uploaded documents
        chat_history:  List of (human_msg, ai_msg) tuples — last N conversations

    Returns:
        (answer_generator, source_docs)
        answer_generator: yields text tokens one at a time (for streaming UI)
        source_docs:      List of Document objects used as context (for citation)
    """

    # ── Phase 1: Retrieval ────────────────────────────────────────────────────
    #
    # similarity_search() converts the query to a vector using the same embedding
    # model, then finds the k=4 stored vectors most similar to it (by cosine distance).
    #
    # Why k=4? This is a tuning parameter:
    # - Too few (k=1): might miss important context
    # - Too many (k=8+): fills the LLM's context window with noise, dilutes relevance
    # - k=4 is a reliable default for most document Q&A use cases
    #
    # Context-aware search: if there is chat history, we enrich the search query
    # with the last exchange so FAISS retrieves chunks relevant to the full
    # conversation — not just the isolated new question in isolation.
    # Example: Q4 asked about "trust", Q5 asks about "decentralised healthcare".
    # Without enrichment, FAISS searches only "decentralised healthcare" and finds
    # nothing. With enrichment, it searches the trust context + new question together
    # and correctly retrieves relevant chunks from both documents.
    if chat_history:
        last_human, last_ai = chat_history[-1]
        enriched_query = f"{last_human} {last_ai[:200]} {query}"
    else:
        enriched_query = query

    source_docs = vector_store.similarity_search(enriched_query, k=4)

    # ── Build Context String ──────────────────────────────────────────────────
    #
    # We format the retrieved chunks into a single context block.
    # Each chunk is prefixed with [From: filename, Page N] — this tells the LLM
    # where the information comes from, which improves citation accuracy.
    context_parts = []
    for doc in source_docs:
        filename = doc.metadata.get("source", "unknown")
        page = doc.metadata.get("page", "?")
        context_parts.append(
            f"[From: {filename}, Page {page}]\n{doc.page_content}"
        )
    context = "\n\n---\n\n".join(context_parts)

    # ── Build Conversation History String ─────────────────────────────────────
    #
    # We include the last 3 turns of conversation so the LLM can handle
    # follow-up questions like "tell me more" or "compare that to X".
    #
    # Why only 3 turns? Groq's free tier has a tokens-per-minute limit.
    # More history = more tokens per request = more likely to hit limits.
    # 3 turns is enough for conversational coherence.
    history_text = ""
    for human_msg, ai_msg in chat_history[-3:]:
        history_text += f"Human: {human_msg}\nAssistant: {ai_msg}\n\n"

    # ── Build the Final Prompt ────────────────────────────────────────────────
    #
    # We use a system message to set the LLM's behaviour, and a user message
    # that contains all the retrieved context + history + the actual question.
    #
    # Key instruction: "based ONLY on the provided context"
    # Without this, the LLM might answer from its training data instead of
    # the uploaded documents — that would be wrong and non-attributable.
    system_message = """You are an intelligent document analyst. Answer questions using the provided document context as your primary source.

Rules:
- Base your answers on the provided document context
- You may reason, infer, and synthesise across multiple documents
- If a question asks you to recommend or compare, use evidence from the documents to support your reasoning even if the exact answer is not explicitly stated
- Only say you cannot find something if the documents contain absolutely no relevant information on the topic
- Be analytical, not just a search engine — draw conclusions from what the documents contain
- When referencing previous conversation, build on it naturally"""

    user_message = f"""Document Context:
{context}

{"Previous conversation:" + chr(10) + history_text if history_text else ""}
Question: {query}

Answer using only the document context above:"""

    # ── Phase 2: Generation (Streaming) ──────────────────────────────────────
    #
    # We use the raw Groq client rather than LangChain's ChatGroq wrapper
    # because it gives us direct access to the streaming generator.
    #
    # st.secrets["GROQ_API_KEY"] reads from .streamlit/secrets.toml locally,
    # or from Streamlit Cloud's Secrets management in production.
    groq_client = Groq(api_key=st.secrets["GROQ_API_KEY"])

    # stream=True changes the response from a single object to an iterator.
    # Each iteration returns a chunk with chunk.choices[0].delta.content
    # which is a small piece of text (sometimes a word, sometimes a token).
    stream = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message}
        ],
        stream=True,
        max_tokens=1024,
        temperature=0.1   # Low temperature = factual, consistent answers
                          # High temperature = creative, variable answers
                          # 0.1 is right for document Q&A
    )

    # ── Stream Generator ──────────────────────────────────────────────────────
    #
    # We wrap the Groq stream in a Python generator function.
    # Generators use 'yield' instead of 'return' — they produce one value
    # at a time instead of collecting everything and returning at the end.
    #
    # This is what enables the word-by-word streaming in the UI:
    # app.py iterates this generator and updates the placeholder with each token.
    #
    # The 'or ""' handles the case where delta.content is None (happens on the
    # final chunk when Groq signals the stream has ended).
    def answer_generator():
        for chunk in stream:
            yield chunk.choices[0].delta.content or ""

    # Return both the generator (for streaming display) and the source docs
    # (for the citation block). app.py handles both.
    return answer_generator(), source_docs
